/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-04-28 21:12:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class repEditReservation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    String repName = (String) session.getAttribute("firstName");
    String role = (String) session.getAttribute("role");

    if (repName == null || !"representative".equalsIgnoreCase(role)) {
        response.sendRedirect("index.jsp");
    }

    String dbUrl = "jdbc:mysql://localhost:3306/airlineproj";
    String dbUser = "root";
    String dbPass = "parshva123";

    Connection conn = null;
    PreparedStatement ticketStmt = null;
    ResultSet ticketRs = null;

    String ticketNumParam = request.getParameter("ticketNum");
    boolean ticketFound = false;

    try {
        if (ticketNumParam != null && !ticketNumParam.isEmpty()) {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(dbUrl, dbUser, dbPass);

            String ticketSql = "SELECT * FROM FlightTicket WHERE ticketNum = ?";
            ticketStmt = conn.prepareStatement(ticketSql);
            ticketStmt.setInt(1, Integer.parseInt(ticketNumParam));
            ticketRs = ticketStmt.executeQuery();

            if (ticketRs.next()) {
                ticketFound = true;
            }
        }
    } catch (Exception e) {
        out.println("<p>Error: " + e.getMessage() + "</p>");
        e.printStackTrace();
    } finally {
        if (!ticketFound && ticketStmt != null) try { ticketStmt.close(); } catch (Exception e) {}
        if (!ticketFound && conn != null) try { conn.close(); } catch (Exception e) {}
    }

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Edit Reservation</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <h2>Edit a Reservation</h2>\n");
      out.write("    <p><a href=\"repWelcome.jsp\">Back to Dashboard</a></p>\n");
      out.write("\n");
      out.write("    <form method=\"get\" action=\"repEditReservation.jsp\">\n");
      out.write("        <label>Enter Ticket Number:</label>\n");
      out.write("        <input type=\"text\" name=\"ticketNum\" required>\n");
      out.write("        <input type=\"submit\" value=\"Search\">\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    ");

        if (ticketFound) {
            int ticketNum = ticketRs.getInt("ticketNum");
            String seat = ticketRs.getString("seat");
            String seatClass = ticketRs.getString("class");
            double totalFare = ticketRs.getDouble("totalFare");
    
      out.write("\n");
      out.write("\n");
      out.write("    <h3>Reservation Details (Ticket #: ");
      out.print( ticketNum );
      out.write(")</h3>\n");
      out.write("    <form method=\"post\" action=\"repEditReservationSubmit.jsp\">\n");
      out.write("        <input type=\"hidden\" name=\"ticketNum\" value=\"");
      out.print( ticketNum );
      out.write("\">\n");
      out.write("\n");
      out.write("        Seat: <input type=\"text\" name=\"seat\" value=\"");
      out.print( seat );
      out.write("\" required><br><br>\n");
      out.write("\n");
      out.write("        Class:\n");
      out.write("        <select name=\"class\" required>\n");
      out.write("            <option value=\"Economy\" ");
      out.print( "Economy".equalsIgnoreCase(seatClass) ? "selected" : "" );
      out.write(">Economy</option>\n");
      out.write("            <option value=\"Business\" ");
      out.print( "Business".equalsIgnoreCase(seatClass) ? "selected" : "" );
      out.write(">Business</option>\n");
      out.write("            <option value=\"First\" ");
      out.print( "First".equalsIgnoreCase(seatClass) ? "selected" : "" );
      out.write(">First</option>\n");
      out.write("        </select><br><br>\n");
      out.write("\n");
      out.write("        Total Fare: <input type=\"number\" name=\"totalFare\" step=\"0.01\" value=\"");
      out.print( totalFare );
      out.write("\" required><br><br>\n");
      out.write("\n");
      out.write("        <input type=\"submit\" value=\"Update Reservation\">\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    ");

        }
        if (ticketRs != null) try { ticketRs.close(); } catch (Exception e) {}
        if (ticketStmt != null) try { ticketStmt.close(); } catch (Exception e) {}
        if (conn != null) try { conn.close(); } catch (Exception e) {}
    
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
