/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-04-28 21:13:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class repManageFlights_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    String repName = (String) session.getAttribute("firstName");
    String role = (String) session.getAttribute("role");

    if (repName == null || !"representative".equalsIgnoreCase(role)) {
        response.sendRedirect("index.jsp");
    }

    String dbUrl = "jdbc:mysql://localhost:3306/airlineproj";
    String dbUser = "root";
    String dbPass = "parshva123";

    Connection conn = null;
    PreparedStatement flightStmt = null;
    ResultSet flightRs = null;

    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn = DriverManager.getConnection(dbUrl, dbUser, dbPass);

        String flightSql = "SELECT flightID, flightNum, daysOfWeek, departure, arrival, baseFare FROM Flight";
        flightStmt = conn.prepareStatement(flightSql);
        flightRs = flightStmt.executeQuery();

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Manage Flights</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <h2>Manage Flights</h2>\n");
      out.write("    <p><a href=\"repWelcome.jsp\">Back to Dashboard</a></p>\n");
      out.write("\n");
      out.write("    <h3>Existing Flights</h3>\n");
      out.write("    <table border=\"1\" cellpadding=\"5\">\n");
      out.write("        <tr>\n");
      out.write("            <th>Flight ID</th>\n");
      out.write("            <th>Flight Number</th>\n");
      out.write("            <th>Days of Week</th>\n");
      out.write("            <th>Departure</th>\n");
      out.write("            <th>Arrival</th>\n");
      out.write("            <th>Base Fare ($)</th>\n");
      out.write("            <th>Actions</th>\n");
      out.write("        </tr>\n");
      out.write("        ");
 while(flightRs.next()) { 
            int flightID = flightRs.getInt("flightID");
        
      out.write("\n");
      out.write("            <tr>\n");
      out.write("                <td>");
      out.print( flightID );
      out.write("</td>\n");
      out.write("                <td>");
      out.print( flightRs.getString("flightNum") );
      out.write("</td>\n");
      out.write("                <td>");
      out.print( flightRs.getString("daysOfWeek") );
      out.write("</td>\n");
      out.write("                <td>");
      out.print( flightRs.getTime("departure") );
      out.write("</td>\n");
      out.write("                <td>");
      out.print( flightRs.getTime("arrival") );
      out.write("</td>\n");
      out.write("                <td>");
      out.print( flightRs.getDouble("baseFare") );
      out.write("</td>\n");
      out.write("                <td>\n");
      out.write("                    <form method=\"get\" action=\"repEditFlight.jsp\">\n");
      out.write("                        <input type=\"hidden\" name=\"flightID\" value=\"");
      out.print( flightID );
      out.write("\">\n");
      out.write("                        <input type=\"submit\" value=\"Edit\">\n");
      out.write("                    </form>\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("    </table>\n");
      out.write("\n");
      out.write("    <h3>Add New Flight</h3>\n");
      out.write("    <form method=\"post\" action=\"repManageFlightsSubmit.jsp\">\n");
      out.write("        Flight Number: <input type=\"text\" name=\"flightNum\" required><br><br>\n");
      out.write("        Days of Week: <input type=\"text\" name=\"daysOfWeek\" placeholder=\"Mon,Wed,Fri\" required><br><br>\n");
      out.write("        Departure Time: <input type=\"time\" name=\"departure\" required><br><br>\n");
      out.write("        Arrival Time: <input type=\"time\" name=\"arrival\" required><br><br>\n");
      out.write("        Base Fare: <input type=\"number\" step=\"0.01\" name=\"baseFare\" required><br><br>\n");
      out.write("\n");
      out.write("        <input type=\"submit\" value=\"Add Flight\">\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");

    } catch(Exception e) {
        out.println("<p>Error: " + e.getMessage() + "</p>");
        e.printStackTrace();
    } finally {
        if(flightRs != null) try { flightRs.close(); } catch(Exception e) {}
        if(flightStmt != null) try { flightStmt.close(); } catch(Exception e) {}
        if(conn != null) try { conn.close(); } catch(Exception e) {}
    }

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
