/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2025-04-28 21:11:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class revenueSummary_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    String name = (String) session.getAttribute("firstName");
    String role = (String) session.getAttribute("role");

    if (name == null || !"admin".equalsIgnoreCase(role)) {
        response.sendRedirect("index.jsp");
    }

    String reportType = request.getParameter("type"); // flight, airline, customer
    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    PreparedStatement topStmt = null;
    ResultSet topRs = null;

    String topLabel = "";
    double topRevenue = 0.0;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head><title>Revenue Summary</title></head>\n");
      out.write("<body>\n");
      out.write("    <h2>Revenue Summary</h2>\n");
      out.write("    <p><a href=\"adminWelcome.jsp\">Back to Admin Dashboard</a></p>\n");
      out.write("\n");
      out.write("    <form method=\"get\" action=\"revenueSummary.jsp\">\n");
      out.write("        View Revenue By: \n");
      out.write("        <select name=\"type\" required>\n");
      out.write("            <option value=\"\">--Select--</option>\n");
      out.write("            <option value=\"flight\" ");
      out.print( "flight".equals(reportType) ? "selected" : "" );
      out.write(">Flight</option>\n");
      out.write("            <option value=\"airline\" ");
      out.print( "airline".equals(reportType) ? "selected" : "" );
      out.write(">Airline</option>\n");
      out.write("            <option value=\"customer\" ");
      out.print( "customer".equals(reportType) ? "selected" : "" );
      out.write(">Customer</option>\n");
      out.write("        </select>\n");
      out.write("        <input type=\"submit\" value=\"Generate\">\n");
      out.write("    </form>\n");
      out.write("\n");

    if (reportType != null && !reportType.trim().isEmpty()) {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlineproj", "root", "parshva123");

            String sql = "";
            String topSql = "";

            if ("flight".equals(reportType)) {
                sql = "SELECT f.flightNum AS label, SUM(ft.totalFare) AS revenue " +
                      "FROM FlightTicket ft JOIN Flight f ON ft.flightID = f.flightID " +
                      "GROUP BY f.flightNum";

                topSql = "SELECT f.flightNum AS topLabel, SUM(ft.totalFare) AS topRevenue " +
                         "FROM FlightTicket ft JOIN Flight f ON ft.flightID = f.flightID " +
                         "GROUP BY f.flightNum ORDER BY topRevenue DESC LIMIT 1";
            } else if ("airline".equals(reportType)) {
                sql = "SELECT al.name AS label, SUM(ft.totalFare) AS revenue " +
                      "FROM FlightTicket ft " +
                      "JOIN Flight f ON ft.flightID = f.flightID " +
                      "JOIN Airline al ON f.airlineID = al.airlineID " +
                      "GROUP BY al.name";
            } else if ("customer".equals(reportType)) {
                sql = "SELECT CONCAT(u.firstName, ' ', u.lastName) AS label, SUM(ft.totalFare) AS revenue " +
                      "FROM FlightTicket ft " +
                      "JOIN CustomerAccount ca ON ft.accountID = ca.accountID " +
                      "JOIN User u ON ca.userID = u.userID " +
                      "GROUP BY u.userID";

                topSql = "SELECT CONCAT(u.firstName, ' ', u.lastName) AS topLabel, SUM(ft.totalFare) AS topRevenue " +
                         "FROM FlightTicket ft " +
                         "JOIN CustomerAccount ca ON ft.accountID = ca.accountID " +
                         "JOIN User u ON ca.userID = u.userID " +
                         "GROUP BY u.userID ORDER BY topRevenue DESC LIMIT 1";
            }

            pstmt = conn.prepareStatement(sql);
            rs = pstmt.executeQuery();

            if (!topSql.isEmpty()) {
                topStmt = conn.prepareStatement(topSql);
                topRs = topStmt.executeQuery();
                if (topRs.next()) {
                    topLabel = topRs.getString("topLabel");
                    topRevenue = topRs.getDouble("topRevenue");
                }
            }

      out.write("\n");
      out.write("\n");
      out.write("    <h3>Revenue Summary by ");
      out.print( reportType.substring(0, 1).toUpperCase() + reportType.substring(1) );
      out.write(":</h3>\n");
      out.write("    <table border=\"1\">\n");
      out.write("        <tr>\n");
      out.write("            <th>");
      out.print( reportType.substring(0, 1).toUpperCase() + reportType.substring(1) );
      out.write("</th>\n");
      out.write("            <th>Total Revenue</th>\n");
      out.write("        </tr>\n");
      out.write("        ");

            boolean hasResults = false;
            while(rs.next()) {
                hasResults = true;
        
      out.write("\n");
      out.write("        <tr>\n");
      out.write("            <td>");
      out.print( rs.getString("label") );
      out.write("</td>\n");
      out.write("            <td>$");
      out.print( rs.getDouble("revenue") );
      out.write("</td>\n");
      out.write("        </tr>\n");
      out.write("        ");

            }
            if (!hasResults) {
        
      out.write("\n");
      out.write("        <tr><td colspan=\"2\">No data available.</td></tr>\n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("    </table>\n");
      out.write("\n");
      out.write("    ");

        if ("customer".equals(reportType) && topLabel != null && !topLabel.isEmpty()) {
    
      out.write("\n");
      out.write("        <h4>Top Customer:</h4>\n");
      out.write("        <p><strong>");
      out.print( topLabel );
      out.write("</strong> with Total Revenue: $");
      out.print( topRevenue );
      out.write("</p>\n");
      out.write("    ");

        } else if ("flight".equals(reportType) && topLabel != null && !topLabel.isEmpty()) {
    
      out.write("\n");
      out.write("        <h4>Most Active Flight:</h4>\n");
      out.write("        <p><strong>Flight ");
      out.print( topLabel );
      out.write("</strong> with Total Revenue: $");
      out.print( topRevenue );
      out.write("</p>\n");
      out.write("    ");

        }
    
      out.write('\n');
      out.write('\n');

        } catch(Exception e) {
            out.println("<p>Error: " + e.getMessage() + "</p>");
            e.printStackTrace();
        } finally {
            if(topRs != null) try { topRs.close(); } catch(Exception e) {}
            if(topStmt != null) try { topStmt.close(); } catch(Exception e) {}
            if(rs != null) try { rs.close(); } catch(Exception e) {}
            if(pstmt != null) try { pstmt.close(); } catch(Exception e) {}
            if(conn != null) try { conn.close(); } catch(Exception e) {}
        }
    }

      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
